server will now use more advanced http servers if available

diff --git a/functions/server b/functions/server
--- a/functions/server
+++ b/functions/server
@@ -1,3 +1,23 @@
+function usage {
+  echo "server <PORT>|-h" 1>&2
+  echo "runs devd, ran or a python web server for the current directory and opens it in the browser" 1>&2
+}
+
+if [ "${1}" = "-h" ]; then
+  usage
+  return
+fi
+
 PORT=${1}
 if [ -z "${PORT}" ]; then PORT=8000; fi
-open "http://localhost:${PORT}" && python -m SimpleHTTPServer $PORT
+
+if (( $+commands[devd] )); then
+  devd --port "${PORT}" --open --livereload .
+elif (( $+commands[ran] )); then
+  open "http://localhost:${PORT}" && ran --port "${PORT}" --listdir
+elif (( $+commands[python] )); then
+  open "http://localhost:${PORT}" && python -m SimpleHTTPServer "${PORT}"
+else
+  echo "ERROR: neither devd, ran or python is installed" 1>&2
+  usage
+fi
